<a href="https://colab.research.google.com/github/alimoorreza/CS167-fall26-notes/blob/main/Day08_Normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS167: Day08
## Data Normalization

#### CS167: Machine Learning, Fall 2026


📜 [Syllabus](https://analytics.drake.edu/~reza/teaching/cs167_fall26/cs167_syllabus_fall26.pdf)

## Before we get started, let's load in our datasets:

In [1]:
#run this cell if you're using Colab:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
#import the data:
import pandas as pd
path = '/content/drive/MyDrive/cs167_fall26/datasets/titanic.csv'
titanic = pd.read_csv(path)
print(f"total number of samples (rows): {titanic.shape[0]}")
print(f"total number of predictors (columns): {titanic.shape[1]}")
titanic.head()

total number of samples (rows): 891
total number of predictors (columns): 15

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

# Normalization:

__Normalizing data:__
- rescale attrbute values so they're about the same
- adjusting values measured on different scales to a common scale

## A Simple Normalization:
One simple method of normalizing data is to replace each value with a proportion relativeto the max value.

For example, the oldest person on the Titanic was 80, so:

| **age** | **replaced by** |
|---------|:------------------|
| 80      | 80/80 = 1        |
| 50      | 50/80 = 0.625    |
| 48      | 48/80 = 0.6      |
| 25      | 25/80 = 0.3125   |
| 4       | 4/80 = 0.05      |

## Before Normalization
<div>
<img src="https://analytics.drake.edu/~reza/teaching/cs167_sp25/notes/images/day03_zscore_improvement.png" width=600/>
</div>

### Age is overemphasized here

## Z-Score: Another Normalization Method

__Idea__: rather than normalize to proportion of max, normalize based on how mnay standard deviations they are away from the mean.

__Standard Deviation__: usually represened as $\sigma$ (sigma), a kind of 'average' distance from the average value.
- a low standard deviation indicates that the values tend to be close to the mean
- a high standard deviation indicates that the values are spread out over a wider range.

## Standard Deviation:
<div>
<img src="https://analytics.drake.edu/~reza/teaching/cs167_sp25/notes/images/day03_std.png" width=400/>
</div>

## Standard Deviation Calculation:

## $\sigma = \sqrt{\frac{1}{N}\sum_{i=1}^{N}(x_i - \mu)^2}$

1. Find the mean, represented as $\mu$ (mu)
2. Then, for each number, subtract the mean and square the result.
3. Then, find the mean of those squared differences.
4. Take the square root of tht and we are done.

Let $\mu$ be the mean, then standard deviation of $x_1, x+2, ..., x_N$ is:

## $\sigma = \sqrt{\frac{(x_1-\mu)^2 + (x_2 - \mu)^2+ ... + (x_N-\mu)^2}{N}}$

# Corrected Sample Standard Deviation

The mean of a sample tends to be a good estimate for the mean of the entire population (on average), but..
- standard deviation of samples tend to be _smaller_ than the standard deviation of the entier population.

__Bessel's correction__ says that you should divide by $N-1$ instead of N when working with a sample (as we usually do in machine learning tasks), and your estimate will be a little less biased.

## $\sigma = \sqrt{\frac{(x_1-\mu)^2 + (x_2 - \mu)^2+ ... + (x_N-\mu)^2}{N-1}}$

# Computing the Z-Score
After computing the corrected sample standard deviation,

to normlaize, replace each value $x_i$ with it's Z-Socre based on the mean ($\mu$) and standard deviation ($\sigma$) of it's column.

## $Z-score: \frac{x_i- \mu}{\sigma}$

## Exampe Z-Score Calculation

For example:

On the Titanic:
- sex mean(0:male, 1:female): 0.35
- sex standard deviation: 0.48
- age mean: 29.7
- age standard deviatios
<div>
<img src="https://analytics.drake.edu/~reza/teaching/cs167_sp25/notes/images/day03_zscore.png" width=400/>
</div>


<div>
<img src="https://analytics.drake.edu/~reza/teaching/cs167_sp25/notes/images/day03_zscore_ex.png" width=600/>
</div>

# Normalization Code:
Let's try out some code now:

In [16]:
#import the data:
import pandas as pd
path = '/content/drive/MyDrive/cs167_fall26/datasets/titanic.csv'
titanic = pd.read_csv(path)
print('total number of columns: ', titanic.shape[1])
titanic.head()

total number of columns:  15

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

# You can use either `replace()` or `get_dummies()` function
## New function `replace()`

Called on a dataframe, will repalce values given in `to_replace` with `value`.

Let's use this to make the `who` column of the dataset numeric.

In [14]:
titanic['who'] = titanic['who'].replace(to_replace='man', value=0) # replacing text value with a numeric value
titanic['who'] = titanic['who'].replace(to_replace='woman', value=1)
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,0,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,1,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,1,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,1,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,0,True,NaN,Southampton,no,True

## New function `pandas.get_dummies()`

Creates a dataframe by repalcing values in a given `column` with `True` or `False` values (using 1-of-K representation).

Let's use this to make the `sex` column of the dataset numeric.

In [17]:
df2 = pd.get_dummies( titanic[ ['sex'] ] )
titanic.drop(columns=['sex'], inplace=True)
titanic = pd.concat( [titanic, df2], axis=1)
titanic.head()

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_female,sex_male
0,0,3,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,False,True
1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,True,False
2,1,3,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True,False
3,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,True,False
4,0,3,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,False,True

## Calculating z-score:
Now that we have the data as 1s and 0s, let's calculate the mean and standard deviation.

In [ ]:
s_mean  = titanic['sex'].mean()
s_std   = titanic['sex'].std()

#replace column with each entry's z-score
titanic['sex'] = (titanic['sex'] - s_mean)/s_std
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,-0.737281,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1.354813,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,1.354813,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,1.354813,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,-0.737281,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
fare_mean       = titanic['fare'].mean()
fare_std        = titanic['fare'].std()

# z-score normalization value for 'fare' column/predictor is as follows:
titanic['fare'] = (titanic['fare'] - fare_mean)/fare_std
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,-0.737281,22.0,1,0,-0.502163,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1.354813,38.0,1,0,0.786404,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,1.354813,26.0,0,0,-0.488580,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,1.354813,35.0,1,0,0.420494,S,First,woman,False,C,Southampton,yes,False
4,0,3,-0.737281,35.0,0,0,-0.486064,S,Third,man,True,NaN,Southampton,no,True

Next, you'd need to repeat this process for all of the predictor columns -- so they're all of compareable size.

## Group Exercise#1:

Normalize each of the predictor columns in the iris dataset.

> Note: you need a way to transform the new reading (the specimen) that you will make the precition on so that the new one and the training data will all be on the same sclae. How can you do that?

Repeat your kNN prediction code with the normalized data. Copy the `kNN()` function you created in our last class.
- Does the value of k change the predictions?

In [18]:
#import the data:
import pandas as pd
path = '/content/drive/MyDrive/cs167_fall26/datasets/irisData.csv'
iris = pd.read_csv(path)
print('total number of columns: ', iris.shape[1])
iris.head()

total number of columns:  5

   sepal length  sepal width  petal length  petal width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
# Normalize each column of iris dataframe

iris_normalized = iris.copy()

mean_sp_l = iris['sepal length'].mean()
std_sp_l = iris['sepal length'].std()
iris_normalized['sepal length'] = (iris['sepal length'] - mean_sp_l)/std_sp_l


# do it for 'sepal width' predictor
# ...
# ...
mean_sp_w = -1
std_sp_w = -1

# do it for 'petal length' predictor
# ...
# ...
mean_p_l = -1
std_p_l = -1


# do it for 'petal width' predictor
# ...
# ...
mean_p_w = -1
std_p_w = -1


means = [float(mean_sp_l), float(mean_sp_w), float(mean_p_l), float(mean_p_w)]
stds = [float(std_sp_l), float(std_sp_w), float(std_p_l), float(std_p_w)]
print('means:', means)
print('std:', stds)

means: [5.843333333333334, 3.0540000000000003, 3.758666666666666, 1.1986666666666668]
std: [0.8280661279778629, 0.4335943113621737, 1.7644204199522617, 0.7631607417008414]

# Normalizing using `StandardScaler`

**Documentation**: [`sklearn.preprocessing.StandardScaler`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)

- Standardize features by removing the mean and scaling to unit variance.
- Centering and scaling happen independently on each feature by computing the relevant statistics on the samples in the training set. Mean and standard deviation are then stored to be used on later data using __transform__.

In [20]:
# import libraries
import pandas
import sklearn

#from sklearn import neighbors # importing the k-Nearest Neighbor machine learning model
from sklearn.neighbors import KNeighborsClassifier

# load data
path = '/content/drive/MyDrive/cs167_fall26/datasets/irisData.csv'
iris_data = pandas.read_csv(path)
iris_data.head()

   sepal length  sepal width  petal length  petal width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

## Step 1.1: Separate the training data

In [21]:
predictors= ['sepal length', 'sepal width', 'petal length', 'petal width']
target= 'species'

train_data      = iris_data[predictors]
train_labels    = iris_data[target]
print('train_data shape:', train_data.shape, 'and train_labels shape:', train_labels.shape)

train_data shape: (150, 4) and train_labels shape: (150,)

## Step 1.2: Generate a new test sample
Let's generate a new instance with:
- 5.1 petal length, 7.2 sepal length, 1.5 petal width, and 2.5 sepal width

In [22]:
# create a new sample test value for which we don't know the 'species' (target variable) value
new_iris = {'sepal length': [7.2], 'sepal width':[2.5], 'petal length':5.5, 'petal width':[1.5]}
test_data = pandas.DataFrame(data=new_iris)
test_data

   sepal length  sepal width  petal length  petal width
0           7.2          2.5           5.5          1.5

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

scaler                  = StandardScaler()

scaler.fit(train_data)                                  # computes the mean and std to be used for later scaling
train_data_normalized   = scaler.transform(train_data)  # performs standardization by centering and scaling on the training features
test_data_normalized    = scaler.transform(test_data)   # performs standardization by centering and scaling on the testing features
#train_data_normalized
print('mean:',scaler.mean_)
print('std:', np.sqrt(scaler.var_))

mean: [5.84333333 3.054      3.75866667 1.19866667]
std: [0.82530129 0.43214658 1.75852918 0.76061262]

# Now normalize vehicle dataset

In [ ]:
# load in the vehicles.csv data for scikit learn
import pandas
import numpy

# load data, get the right subset
path = '/content/drive/MyDrive/cs167_fall26/datasets/vehicles.csv'
data = pandas.read_csv(path)
gas_vehicles = data[data['fuelType']=='Regular'][['year', 'cylinders', 'displ', 'comb08']]
gas_vehicles.dropna(inplace=True)

# set the predictor variables and target variable
predictors= ['year', 'cylinders', 'displ']
target= 'comb08'

# separate the data and labels
train_data   = gas_vehicles[predictors]
train_labels = gas_vehicles[target]
print('train_data shape:', train_data.shape, 'and train_labels shape:', train_labels.shape)


# create a new sample test (with three predictors) but for which we don't know the 'comb08' (target variable) value
new_vehicle = {'year': [1985], 'cylinders':[4], 'displ':2.0}
test_data = pandas.DataFrame(data=new_vehicle)
test_data

# Group Exercise: Normalizing using `StandardScaler`

In [ ]:
from sklearn.preprocessing import StandardScaler
# your code
# ...
# ...