<a href="https://colab.research.google.com/github/alimoorreza/CS167-fall26-notes/blob/main/Day02_Pandas_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS167: Day02
## 🐼 Pandas Tutorial (Introduction)

#### CS167: Machine Learning, Fall 2026


📜 [Syllabus](https://analytics.drake.edu/~reza/teaching/cs167_fall26/cs167_syllabus_fall26.pdf)

# 🐼 Pandas
__Pandas__ is a super powerful Python data analysis library.
- it's built on top of another super powerful libray called `numpy`

Using Google Colab, `pandas` should already be installed. If you see `In [*]` next to a cell, it means your computer is working on the task.

## Overview of Pandas Tutorial

Three main goals:
1. __Overview__ of Pandas
    - Datatypes `DataFrame` and `Series`
    - helpful functions
2. Select __columns__ in DataFrames
3. Select __rows__ in DataFrames
4. Select __subsets__ of the DataFrame (both rows and columns).

##  Pandas Datatypes: `DataFrame` and `Series`

In `pandas`,there are two main datatypes, `DataFrame` and `Series`:

Let's start with `DataFrame`

[Pandas Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html) defines `DataFrames` as:
> Two-dimensional, size-mutable, potentially heterogeneous tabular data.

- basically, think of `DataFrames` as our excel sheets--two dimensional, tabular data.
- Each column has a name, and you can use these names to filter and create subsets of data.
- often, you'll see `DataFrames` abbreviated to `df`.

In [ ]:
# The first step is to mount your Google Drive to your Colab account.
#You will be asked to authorize Colab to access your Google Drive. Follow the steps they lead you throuh.

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
import pandas
df_rest = pandas.read_csv('/content/drive/MyDrive/cs167_fall26/datasets/restaurant.csv')
df_rest.head(6)

   alt  bar  fri  hun   pat price rain  res     type    est target
0  Yes   No   No  Yes  Some   $$$   No  Yes   French   0-10    Yes
1  Yes   No   No  Yes  Full     $   No   No     Thai  30-60     No
2   No  Yes   No   No  Some     $   No   No   Burger   0-10    Yes
3  Yes   No  Yes  Yes  Full     $   No   No     Thai  10-30    Yes
4  Yes   No  Yes   No  Full   $$$   No  Yes   French    >60     No
5   No  Yes   No  Yes  Some    $$  Yes  Yes  Italian   0-10    Yes

In [13]:
import pandas
df_titanic = pandas.read_csv('/content/drive/MyDrive/cs167_fall26/datasets/titanic.csv')
df_titanic.head(7)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True

### 📣 Helpful Attributes
>> `df.columns`, `df.iloc[]`, etc

>> we are going explore more on these later

In [5]:
titanic.iloc[0]

survived                 0
pclass                   3
sex                   male
age                   22.0
sibsp                    1
parch                    0
fare                  7.25
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                False
Name: 0, dtype: object

## Columns Names

Want to see a list of all of the columns in your dataset? Try using `df.columns`

In [14]:
col = df_rest.columns
col

Index(['alt', 'bar', 'fri', 'hun', 'pat', 'price', 'rain', 'res', 'type',
       'est', 'target'],
      dtype='object')

If there are no spaces in the name of a column, you can also reference it using dot notation like so:

In [15]:
df_rest.type # seeing the values of different rows in the column named 'type'

0      French
1        Thai
2      Burger
3        Thai
4      French
5     Italian
6      Burger
7        Thai
8      Burger
9     Italian
10       Thai
11     Burger
Name: type, dtype: object

## Selecting Rows in DataFrames using `loc` and `iloc`:
Simply put:
- `loc` gets DataFrame rows and columns by __labels/names__
- `iloc` gets DataFrame rows and columns by __index/position__

###Selecting rows in a DataFrame
`loc` gets DataFrame rows and columns by __labels/names__

In [17]:
print(df_titanic.loc[0])   # 1 is really a "name", not a number

survived                 0
pclass                   3
sex                   male
age                   22.0
sibsp                    1
parch                    0
fare                  7.25
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                False
Name: 0, dtype: object

In [18]:
print(df_titanic.loc[880])   # 880 is really a "name", not a number

survived                 1
pclass                   2
sex                 female
age                   25.0
sibsp                    0
parch                    1
fare                  26.0
embarked                 S
class               Second
who                  woman
adult_male           False
deck                   NaN
embark_town    Southampton
alive                  yes
alone                False
Name: 880, dtype: object

Let's take a subset of titanic and try to use `loc` and `iloc`:

In [19]:
subset = df_titanic.loc[1:6] # since it's a label, it will take rows labeled 1, 2, 3, 4, 5, and 6.
print(subset)

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third
5         0       3    male   NaN      0      0   8.4583        Q  Third
6         0       1    male  54.0      0      0  51.8625        S  First

     who  adult_male deck  embark_town alive  alone
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True
5    man        True  NaN   Queenstown    no   True
6    man        True    E  Southampton    no   True

In [ ]:
subset = df_titanic.loc[800:805] # since it's a label, it will take rows labeled 800, 801, 802, 803, 804, and 805.
print(subset)

     survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
800         0       2    male  34.00      0      0   13.0000        S  Second
801         1       2  female  31.00      1      1   26.2500        S  Second
802         1       1    male  11.00      1      2  120.0000        S   First
803         1       3    male   0.42      0      1    8.5167        C   Third
804         1       3    male  27.00      0      0    6.9750        S   Third
805         0       3    male  31.00      0      0    7.7750        S   Third

       who  adult_male deck  embark_town alive  alone
800    man        True  NaN  Southampton    no   True
801  woman       False  NaN  Southampton   yes  False
802  child       False    B  Southampton   yes  False
803  child       False  NaN    Cherbourg   yes  False
804    man        True  NaN  Southampton   yes   True
805    man        True  NaN  Southampton    no   True

In [ ]:
subset.loc[800] # will show the 1st row in the DataFrame called 'subset'

survived                 0
pclass                   2
sex                   male
age                   34.0
sibsp                    0
parch                    0
fare                  13.0
embarked                 S
class               Second
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                 True
Name: 800, dtype: object

In [ ]:
subset.loc[805] # will show the 6th row in the DataFrame called 'subset'

survived                 0
pclass                   3
sex                   male
age                   31.0
sibsp                    0
parch                    0
fare                 7.775
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                 True
Name: 805, dtype: object

In [ ]:
subset.loc[806] # DataFrame called 'subset' has only 6 rows, hence ERROR

KeyError: 806

###Selecting Rows in a DataFrame
`iloc` gets DataFrame rows and columns by __index/position__

In [ ]:
subset.iloc[5]  #works

survived                 0
pclass                   3
sex                   male
age                   31.0
sibsp                    0
parch                    0
fare                 7.775
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                 True
Name: 805, dtype: object

## Pandas Datatypes: `Series`
- `Series` are 1D arrays with axis labels.
    - Each __row__ in a DataFrame is a `Series`.
    - Each __column__ in a DataFrame is also a `Series`.

In [ ]:
print(type(df_rest.iloc[0])) #the first row in the dataframe
print(type(df_rest['type'])) #the column 'type' from the dataframe

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

# Subsetting Columns

---


<div>
<img src="https://analytics.drake.edu/~reza/teaching/cs167_sp25//notes/images/day02_subset_cols.png"/ width=600>
</div>

Why might we want a subset of the columns of a DataFrame?

Sometimes you don't need all of the columns and just want to work with a __subset__ of the colummns of the original dataset. Other times, you may want to reorder the columns in your dataset.

Here's how you would do either of those:
The syntax for subsetting columns from a DataFrame (`df`) is:
- One column: `df['column_name']`
- Multiple columns: `df[['column1', 'column2', 'target']]`

So, if we wanted to look at the `price` column, we could do:

In [ ]:
prices = df_rest['price']
prices.head()

0    $$$
1      $
2      $
3      $
4    $$$
Name: price, dtype: object

## Column Subset Example:

Imagine you want to only work with `'rain'`, `'hun'`, and `'target'` from the 'restaurant' dataset:

In [ ]:
prices = df_rest[ ['rain', 'hun', 'target'] ]
prices.head()

  rain  hun target
0   No  Yes    Yes
1   No  Yes     No
2   No   No    Yes
3   No  Yes    Yes
4   No   No     No

Maybe you want to re-order your new subset so that `rain` and `hun` are switched:

In [ ]:
prices_reordered = df_rest[ ['hun', 'rain', 'target'] ]
prices_reordered.head()

   hun rain target
0  Yes   No    Yes
1  Yes   No     No
2   No   No    Yes
3  Yes   No    Yes
4   No   No     No

## 💬 Group Exercise:

Download the Titanic Dataset from Blackboard, upload it to a spot in your GoogleDrive; you might have already done so by now.

See if you can make the following subsets:
- make a subset called `ages` that holds the ages of the passengers on the titanic
- create a subset called `titanic_subset` with the columns `survived`, `deck`, `sex`, and `age`, in that order.

In [ ]:
import pandas as pd
df_titanic = pd.read_csv('/content/drive/MyDrive/cs167_fall26/datasets/titanic.csv') #make sure the path on the line below corresponds to the path where you put your dataset.
df_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# your code
# ...

In [ ]:
row_subset = df_titanic[ df_titanic['survived']==0 ]
row_subset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False

In [ ]:
row_subset = df_titanic.loc[ df_titanic['survived']==0 ]
row_subset.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False